<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shop_countries')->insert([
            ['id' => 1, 'sortname' => 'AF', 'name' => 'Afghanistan', 'phonecode' => 93, 'status' => 0],
            ['id' => 2, 'sortname' => 'AL', 'name' => 'Albania', 'phonecode' => 355, 'status' => 0],
            ['id' => 3, 'sortname' => 'DZ', 'name' => 'Algeria', 'phonecode' => 213, 'status' => 0],
            ['id' => 4, 'sortname' => 'AS', 'name' => 'American Samoa', 'phonecode' => 1684, 'status' => 0],
            ['id' => 5, 'sortname' => 'AD', 'name' => 'Andorra', 'phonecode' => 376, 'status' => 0],
            ['id' => 6, 'sortname' => 'AO', 'name' => 'Angola', 'phonecode' => 244, 'status' => 0],
            ['id' => 7, 'sortname' => 'AI', 'name' => 'Anguilla', 'phonecode' => 1264, 'status' => 0],
            ['id' => 8, 'sortname' => 'AQ', 'name' => 'Antarctica', 'phonecode' => 0, 'status' => 0],
            ['id' => 9, 'sortname' => 'AG', 'name' => 'Antigua And Barbuda', 'phonecode' => 1268, 'status' => 0],
            ['id' => 10, 'sortname' => 'AR', 'name' => 'Argentina', 'phonecode' => 54, 'status' => 0],
            ['id' => 11, 'sortname' => 'AM', 'name' => 'Armenia', 'phonecode' => 374, 'status' => 0],
            ['id' => 12, 'sortname' => 'AW', 'name' => 'Aruba', 'phonecode' => 297, 'status' => 0],
            ['id' => 13, 'sortname' => 'AU', 'name' => 'Australia', 'phonecode' => 61, 'status' => 1],
            ['id' => 14, 'sortname' => 'AT', 'name' => 'Austria', 'phonecode' => 43, 'status' => 0],
            ['id' => 15, 'sortname' => 'AZ', 'name' => 'Azerbaijan', 'phonecode' => 994, 'status' => 0],
            ['id' => 16, 'sortname' => 'BS', 'name' => 'Bahamas The', 'phonecode' => 1242, 'status' => 0],
            ['id' => 17, 'sortname' => 'BH', 'name' => 'Bahrain', 'phonecode' => 973, 'status' => 0],
            ['id' => 18, 'sortname' => 'BD', 'name' => 'Bangladesh', 'phonecode' => 880, 'status' => 0],
            ['id' => 19, 'sortname' => 'BB', 'name' => 'Barbados', 'phonecode' => 1246, 'status' => 0],
            ['id' => 20, 'sortname' => 'BY', 'name' => 'Belarus', 'phonecode' => 375, 'status' => 0],
            ['id' => 21, 'sortname' => 'BE', 'name' => 'Belgium', 'phonecode' => 32, 'status' => 0],
            ['id' => 22, 'sortname' => 'BZ', 'name' => 'Belize', 'phonecode' => 501, 'status' => 0],
            ['id' => 23, 'sortname' => 'BJ', 'name' => 'Benin', 'phonecode' => 229, 'status' => 0],
            ['id' => 24, 'sortname' => 'BM', 'name' => 'Bermuda', 'phonecode' => 1441, 'status' => 0],
            ['id' => 25, 'sortname' => 'BT', 'name' => 'Bhutan', 'phonecode' => 975, 'status' => 0],
            ['id' => 26, 'sortname' => 'BO', 'name' => 'Bolivia', 'phonecode' => 591, 'status' => 0],
            ['id' => 27, 'sortname' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phonecode' => 387, 'status' => 0],
            ['id' => 28, 'sortname' => 'BW', 'name' => 'Botswana', 'phonecode' => 267, 'status' => 0],
            ['id' => 29, 'sortname' => 'BV', 'name' => 'Bouvet Island', 'phonecode' => 0, 'status' => 0],
            ['id' => 30, 'sortname' => 'BR', 'name' => 'Brazil', 'phonecode' => 55, 'status' => 0],
            ['id' => 31, 'sortname' => 'IO', 'name' => 'British Indian Ocean Territory', 'phonecode' => 246, 'status' => 0],
            ['id' => 32, 'sortname' => 'BN', 'name' => 'Brunei', 'phonecode' => 673, 'status' => 0],
            ['id' => 33, 'sortname' => 'BG', 'name' => 'Bulgaria', 'phonecode' => 359, 'status' => 0],
            ['id' => 34, 'sortname' => 'BF', 'name' => 'Burkina Faso', 'phonecode' => 226, 'status' => 0],
            ['id' => 35, 'sortname' => 'BI', 'name' => 'Burundi', 'phonecode' => 257, 'status' => 0],
            ['id' => 36, 'sortname' => 'KH', 'name' => 'Cambodia', 'phonecode' => 855, 'status' => 0],
            ['id' => 37, 'sortname' => 'CM', 'name' => 'Cameroon', 'phonecode' => 237, 'status' => 0],
            ['id' => 38, 'sortname' => 'CA', 'name' => 'Canada', 'phonecode' => 1, 'status' => 1],
            ['id' => 39, 'sortname' => 'CV', 'name' => 'Cape Verde', 'phonecode' => 238, 'status' => 0],
            ['id' => 40, 'sortname' => 'KY', 'name' => 'Cayman Islands', 'phonecode' => 1345, 'status' => 0],
            ['id' => 41, 'sortname' => 'CF', 'name' => 'Central African Republic', 'phonecode' => 236, 'status' => 0],
            ['id' => 42, 'sortname' => 'TD', 'name' => 'Chad', 'phonecode' => 235, 'status' => 0],
            ['id' => 43, 'sortname' => 'CL', 'name' => 'Chile', 'phonecode' => 56, 'status' => 0],
            ['id' => 44, 'sortname' => 'CN', 'name' => 'China', 'phonecode' => 86, 'status' => 0],
            ['id' => 45, 'sortname' => 'CX', 'name' => 'Christmas Island', 'phonecode' => 61, 'status' => 0],
            ['id' => 46, 'sortname' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phonecode' => 672, 'status' => 0],
            ['id' => 47, 'sortname' => 'CO', 'name' => 'Colombia', 'phonecode' => 57, 'status' => 0],
            ['id' => 48, 'sortname' => 'KM', 'name' => 'Comoros', 'phonecode' => 269, 'status' => 0],
            ['id' => 49, 'sortname' => 'CG', 'name' => 'Republic Of The Congo', 'phonecode' => 242, 'status' => 0],
            ['id' => 50, 'sortname' => 'CD', 'name' => 'Democratic Republic Of The Congo', 'phonecode' => 242, 'status' => 0],
            ['id' => 51, 'sortname' => 'CK', 'name' => 'Cook Islands', 'phonecode' => 682, 'status' => 0],
            ['id' => 52, 'sortname' => 'CR', 'name' => 'Costa Rica', 'phonecode' => 506, 'status' => 0],
            ['id' => 53, 'sortname' => 'CI', 'name' => 'Cote D\'Ivoire', 'phonecode' => 225, 'status' => 0],
            ['id' => 54, 'sortname' => 'HR', 'name' => 'Croatia', 'phonecode' => 385, 'status' => 0],
            ['id' => 55, 'sortname' => 'CU', 'name' => 'Cuba', 'phonecode' => 53, 'status' => 0],
            ['id' => 56, 'sortname' => 'CY', 'name' => 'Cyprus', 'phonecode' => 357, 'status' => 0],
            ['id' => 57, 'sortname' => 'CZ', 'name' => 'Czech Republic', 'phonecode' => 420, 'status' => 0],
            ['id' => 58, 'sortname' => 'DK', 'name' => 'Denmark', 'phonecode' => 45, 'status' => 0],
            ['id' => 59, 'sortname' => 'DJ', 'name' => 'Djibouti', 'phonecode' => 253, 'status' => 0],
            ['id' => 60, 'sortname' => 'DM', 'name' => 'Dominica', 'phonecode' => 1767, 'status' => 0],
            ['id' => 61, 'sortname' => 'DO', 'name' => 'Dominican Republic', 'phonecode' => 1849, 'status' => 0],
            ['id' => 62, 'sortname' => 'EC', 'name' => 'Ecuador', 'phonecode' => 593, 'status' => 0],
            ['id' => 63, 'sortname' => 'EG', 'name' => 'Egypt', 'phonecode' => 20, 'status' => 0],
            ['id' => 64, 'sortname' => 'SV', 'name' => 'El Salvador', 'phonecode' => 503, 'status' => 0],
            ['id' => 65, 'sortname' => 'GQ', 'name' => 'Equatorial Guinea', 'phonecode' => 240, 'status' => 0],
            ['id' => 66, 'sortname' => 'ER', 'name' => 'Eritrea', 'phonecode' => 291, 'status' => 0],
            ['id' => 67, 'sortname' => 'EE', 'name' => 'Estonia', 'phonecode' => 372, 'status' => 0],
            ['id' => 68, 'sortname' => 'ET', 'name' => 'Ethiopia', 'phonecode' => 251, 'status' => 0],
            ['id' => 69, 'sortname' => 'FK', 'name' => 'Falkland Islands', 'phonecode' => 500, 'status' => 0],
            ['id' => 70, 'sortname' => 'FO', 'name' => 'Faroe Islands', 'phonecode' => 298, 'status' => 0],
            ['id' => 71, 'sortname' => 'FJ', 'name' => 'Fiji', 'phonecode' => 679, 'status' => 0],
            ['id' => 72, 'sortname' => 'FI', 'name' => 'Finland', 'phonecode' => 358, 'status' => 0],
            ['id' => 73, 'sortname' => 'FR', 'name' => 'France', 'phonecode' => 33, 'status' => 1],
            ['id' => 76, 'sortname' => 'GF', 'name' => 'French Guiana', 'phonecode' => 594, 'status' => 0],
        ['id' => 77, 'sortname' => 'PF', 'name' => 'French Polynesia', 'phonecode' => 689, 'status' => 0],
        ['id' => 78, 'sortname' => 'TF', 'name' => 'French Southern Territories', 'phonecode' => 0, 'status' => 0],
        ['id' => 79, 'sortname' => 'GA', 'name' => 'Gabon', 'phonecode' => 241, 'status' => 0],
        ['id' => 80, 'sortname' => 'GM', 'name' => 'Gambia The', 'phonecode' => 220, 'status' => 0],
        ['id' => 81, 'sortname' => 'GE', 'name' => 'Georgia', 'phonecode' => 995, 'status' => 0],
        ['id' => 82, 'sortname' => 'DE', 'name' => 'Germany', 'phonecode' => 49, 'status' => 0],
        ['id' => 83, 'sortname' => 'GH', 'name' => 'Ghana', 'phonecode' => 233, 'status' => 0],
        ['id' => 84, 'sortname' => 'GI', 'name' => 'Gibraltar', 'phonecode' => 350, 'status' => 0],
        ['id' => 85, 'sortname' => 'GR', 'name' => 'Greece', 'phonecode' => 30, 'status' => 0],
        ['id' => 86, 'sortname' => 'GL', 'name' => 'Greenland', 'phonecode' => 299, 'status' => 0],
        ['id' => 87, 'sortname' => 'GD', 'name' => 'Grenada', 'phonecode' => 1473, 'status' => 0],
        ['id' => 88, 'sortname' => 'GP', 'name' => 'Guadeloupe', 'phonecode' => 590, 'status' => 0],
        ['id' => 89, 'sortname' => 'GU', 'name' => 'Guam', 'phonecode' => 1671, 'status' => 0],
        ['id' => 90, 'sortname' => 'GT', 'name' => 'Guatemala', 'phonecode' => 502, 'status' => 0],
        ['id' => 91, 'sortname' => 'XU', 'name' => 'Guernsey and Alderney', 'phonecode' => 44, 'status' => 0],
        ['id' => 92, 'sortname' => 'GN', 'name' => 'Guinea', 'phonecode' => 224, 'status' => 0],
        ['id' => 93, 'sortname' => 'GW', 'name' => 'Guinea-Bissau', 'phonecode' => 245, 'status' => 0],
        ['id' => 94, 'sortname' => 'GY', 'name' => 'Guyana', 'phonecode' => 592, 'status' => 0],
        ['id' => 95, 'sortname' => 'HT', 'name' => 'Haiti', 'phonecode' => 509, 'status' => 0],
        ['id' => 96, 'sortname' => 'HM', 'name' => 'Heard and McDonald Islands', 'phonecode' => 0, 'status' => 0],
        ['id' => 97, 'sortname' => 'HN', 'name' => 'Honduras', 'phonecode' => 504, 'status' => 0],
        ['id' => 98, 'sortname' => 'HK', 'name' => 'Hong Kong S.A.R.', 'phonecode' => 852, 'status' => 0],
        ['id' => 99, 'sortname' => 'HU', 'name' => 'Hungary', 'phonecode' => 36, 'status' => 0],
        ['id' => 100, 'sortname' => 'IS', 'name' => 'Iceland', 'phonecode' => 354, 'status' => 0],
        ['id' => 101, 'sortname' => 'IN', 'name' => 'India', 'phonecode' => 91, 'status' => 1],
        ['id' => 102, 'sortname' => 'ID', 'name' => 'Indonesia', 'phonecode' => 62, 'status' => 0],
        ['id' => 103, 'sortname' => 'IR', 'name' => 'Iran', 'phonecode' => 98, 'status' => 0],
        ['id' => 104, 'sortname' => 'IQ', 'name' => 'Iraq', 'phonecode' => 964, 'status' => 0],
        ['id' => 105, 'sortname' => 'IE', 'name' => 'Ireland', 'phonecode' => 353, 'status' => 0],
        ['id' => 106, 'sortname' => 'IL', 'name' => 'Israel', 'phonecode' => 972, 'status' => 0],
        ['id' => 107, 'sortname' => 'IT', 'name' => 'Italy', 'phonecode' => 39, 'status' => 0],
        ['id' => 108, 'sortname' => 'JM', 'name' => 'Jamaica', 'phonecode' => 1876, 'status' => 0],
        ['id' => 109, 'sortname' => 'JP', 'name' => 'Japan', 'phonecode' => 81, 'status' => 0],
        ['id' => 110, 'sortname' => 'XJ', 'name' => 'Jersey', 'phonecode' => 44, 'status' => 0],
        ['id' => 111, 'sortname' => 'JO', 'name' => 'Jordan', 'phonecode' => 962, 'status' => 0],
        ['id' => 112, 'sortname' => 'KZ', 'name' => 'Kazakhstan', 'phonecode' => 7, 'status' => 0],
        ['id' => 113, 'sortname' => 'KE', 'name' => 'Kenya', 'phonecode' => 254, 'status' => 0],
        ['id' => 114, 'sortname' => 'KI', 'name' => 'Kiribati', 'phonecode' => 686, 'status' => 0],
        ['id' => 115, 'sortname' => 'KP', 'name' => 'Korea North', 'phonecode' => 850, 'status' => 0],
        ['id' => 116, 'sortname' => 'KR', 'name' => 'Korea South', 'phonecode' => 82, 'status' => 0],
        ['id' => 117, 'sortname' => 'KW', 'name' => 'Kuwait', 'phonecode' => 965, 'status' => 0],
        ['id' => 118, 'sortname' => 'KG', 'name' => 'Kyrgyzstan', 'phonecode' => 996, 'status' => 0],
        ['id' => 119, 'sortname' => 'LA', 'name' => 'Laos', 'phonecode' => 856, 'status' => 0],
        ['id' => 120, 'sortname' => 'LV', 'name' => 'Latvia', 'phonecode' => 371, 'status' => 0],
        ['id' => 121, 'sortname' => 'LB', 'name' => 'Lebanon', 'phonecode' => 961, 'status' => 0],
        ['id' => 122, 'sortname' => 'LS', 'name' => 'Lesotho', 'phonecode' => 266, 'status' => 0],
        ['id' => 123, 'sortname' => 'LR', 'name' => 'Liberia', 'phonecode' => 231, 'status' => 0],
        ['id' => 124, 'sortname' => 'LY', 'name' => 'Libya', 'phonecode' => 218, 'status' => 0],
        ['id' => 125, 'sortname' => 'LI', 'name' => 'Liechtenstein', 'phonecode' => 423, 'status' => 0],
        ['id' => 126, 'sortname' => 'LT', 'name' => 'Lithuania', 'phonecode' => 370, 'status' => 0],
        ['id' => 127, 'sortname' => 'LU', 'name' => 'Luxembourg', 'phonecode' => 352, 'status' => 0],
        ['id' => 128, 'sortname' => 'MO', 'name' => 'Macau S.A.R.', 'phonecode' => 853, 'status' => 0],
        ['id' => 129, 'sortname' => 'MK', 'name' => 'Macedonia', 'phonecode' => 389, 'status' => 0],
        ['id' => 130, 'sortname' => 'MG', 'name' => 'Madagascar', 'phonecode' => 261, 'status' => 0],
        ['id' => 131, 'sortname' => 'MY', 'name' => 'Malaysia', 'phonecode' => 60, 'status' => 0],
        ['id' => 132, 'sortname' => 'MW', 'name' => 'Malawi', 'phonecode' => 265, 'status' => 0],
        ['id' => 133, 'sortname' => 'MV', 'name' => 'Maldives', 'phonecode' => 960, 'status' => 0],
        ['id' => 134, 'sortname' => 'ML', 'name' => 'Mali', 'phonecode' => 223, 'status' => 0],
        ['id' => 135, 'sortname' => 'MT', 'name' => 'Malta', 'phonecode' => 356, 'status' => 0],
        ['id' => 136, 'sortname' => 'MH', 'name' => 'Marshall Islands', 'phonecode' => 692, 'status' => 0],
        ['id' => 137, 'sortname' => 'MQ', 'name' => 'Martinique', 'phonecode' => 596, 'status' => 0],
        ['id' => 138, 'sortname' => 'MR', 'name' => 'Mauritania', 'phonecode' => 222, 'status' => 0],
        ['id' => 139, 'sortname' => 'MU', 'name' => 'Mauritius', 'phonecode' => 230, 'status' => 0],
        ['id' => 140, 'sortname' => 'YT', 'name' => 'Mayotte', 'phonecode' => 262, 'status' => 0],
        ['id' => 141, 'sortname' => 'MX', 'name' => 'Mexico', 'phonecode' => 52, 'status' => 0],
        ['id' => 142, 'sortname' => 'FM', 'name' => 'Micronesia', 'phonecode' => 691, 'status' => 0],
        ['id' => 143, 'sortname' => 'MD', 'name' => 'Moldova', 'phonecode' => 373, 'status' => 0],
        ['id' => 144, 'sortname' => 'MC', 'name' => 'Monaco', 'phonecode' => 377, 'status' => 0],
        ['id' => 145, 'sortname' => 'MN', 'name' => 'Mongolia', 'phonecode' => 976, 'status' => 0],
        ['id' => 146, 'sortname' => 'ME', 'name' => 'Montenegro', 'phonecode' => 382, 'status' => 0],
        ['id' => 147, 'sortname' => 'MS', 'name' => 'Montserrat', 'phonecode' => 1664, 'status' => 0],
        ['id' => 148, 'sortname' => 'MA', 'name' => 'Morocco', 'phonecode' => 212, 'status' => 0],
        ['id' => 149, 'sortname' => 'MZ', 'name' => 'Mozambique', 'phonecode' => 258, 'status' => 0],
        ['id' => 150, 'sortname' => 'MM', 'name' => 'Myanmar', 'phonecode' => 95, 'status' => 0],
        ['id' => 151, 'sortname' => 'NA', 'name' => 'Namibia', 'phonecode' => 264, 'status' => 0],
        ['id' => 152, 'sortname' => 'NR', 'name' => 'Nauru', 'phonecode' => 674, 'status' => 0],
        ['id' => 153, 'sortname' => 'NP', 'name' => 'Nepal', 'phonecode' => 977, 'status' => 0],
        ['id' => 154, 'sortname' => 'AN', 'name' => 'Netherlands Antilles', 'phonecode' => 599, 'status' => 0],
        ['id' => 155, 'sortname' => 'NL', 'name' => 'Netherlands The', 'phonecode' => 31, 'status' => 0],
        ['id' => 156, 'sortname' => 'NC', 'name' => 'New Caledonia', 'phonecode' => 687, 'status' => 0],
        ['id' => 157, 'sortname' => 'NZ', 'name' => 'New Zealand', 'phonecode' => 64, 'status' => 0],
        ['id' => 158, 'sortname' => 'NI', 'name' => 'Nicaragua', 'phonecode' => 505, 'status' => 0],
        ['id' => 159, 'sortname' => 'NE', 'name' => 'Niger', 'phonecode' => 227, 'status' => 0],
        ['id' => 160, 'sortname' => 'NG', 'name' => 'Nigeria', 'phonecode' => 234, 'status' => 0],
        ['id' => 161, 'sortname' => 'NU', 'name' => 'Niue', 'phonecode' => 683, 'status' => 0],
        ['id' => 162, 'sortname' => 'NF', 'name' => 'Norfolk Island', 'phonecode' => 672, 'status' => 0],
        ['id' => 163, 'sortname' => 'MP', 'name' => 'Northern Mariana Islands', 'phonecode' => 1670, 'status' => 0],
        ['id' => 164, 'sortname' => 'NO', 'name' => 'Norway', 'phonecode' => 47, 'status' => 0],
        ['id' => 165, 'sortname' => 'OM', 'name' => 'Oman', 'phonecode' => 968, 'status' => 0],
        ['id' => 166, 'sortname' => 'PK', 'name' => 'Pakistan', 'phonecode' => 92, 'status' => 0],
        ['id' => 167, 'sortname' => 'PW', 'name' => 'Palau', 'phonecode' => 680, 'status' => 0],
        ['id' => 168, 'sortname' => 'PS', 'name' => 'Palestinian Territory Occupied', 'phonecode' => 970, 'status' => 0],
        ['id' => 169, 'sortname' => 'PA', 'name' => 'Panama', 'phonecode' => 507, 'status' => 0],
        ['id' => 170, 'sortname' => 'PG', 'name' => 'Papua new Guinea', 'phonecode' => 675, 'status' => 0],
        ['id' => 171, 'sortname' => 'PY', 'name' => 'Paraguay', 'phonecode' => 595, 'status' => 0],
        ['id' => 172, 'sortname' => 'PE', 'name' => 'Peru', 'phonecode' => 51, 'status' => 0],
        ['id' => 173, 'sortname' => 'PH', 'name' => 'Philippines', 'phonecode' => 63, 'status' => 0],
        ['id' => 174, 'sortname' => 'PN', 'name' => 'Pitcairn Island', 'phonecode' => 0, 'status' => 0],
        ['id' => 175, 'sortname' => 'PL', 'name' => 'Poland', 'phonecode' => 48, 'status' => 0],
        ['id' => 176, 'sortname' => 'PT', 'name' => 'Portugal', 'phonecode' => 351, 'status' => 0],
        ['id' => 177, 'sortname' => 'PR', 'name' => 'Puerto Rico', 'phonecode' => 1787, 'status' => 0],
        ['id' => 178, 'sortname' => 'QA', 'name' => 'Qatar', 'phonecode' => 974, 'status' => 0],
        ['id' => 179, 'sortname' => 'RE', 'name' => 'Reunion', 'phonecode' => 262, 'status' => 0],
        ['id' => 180, 'sortname' => 'RO', 'name' => 'Romania', 'phonecode' => 40, 'status' => 0],
        ['id' => 181, 'sortname' => 'RU', 'name' => 'Russia', 'phonecode' => 70, 'status' => 0],
        ['id' => 182, 'sortname' => 'RW', 'name' => 'Rwanda', 'phonecode' => 250, 'status' => 0],
        ['id' => 183, 'sortname' => 'SH', 'name' => 'Saint Helena', 'phonecode' => 290, 'status' => 0],
        ['id' => 184, 'sortname' => 'KN', 'name' => 'Saint Kitts And Nevis', 'phonecode' => 1869, 'status' => 0],
        ['id' => 185, 'sortname' => 'LC', 'name' => 'Saint Lucia', 'phonecode' => 1758, 'status' => 0],
        ['id' => 186, 'sortname' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'phonecode' => 508, 'status' => 0],
        ['id' => 187, 'sortname' => 'VC', 'name' => 'Saint Vincent And The Grenadines', 'phonecode' => 1784, 'status' => 0],
        ['id' => 188, 'sortname' => 'WS', 'name' => 'Samoa', 'phonecode' => 684, 'status' => 0],
        ['id' => 189, 'sortname' => 'SM', 'name' => 'San Marino', 'phonecode' => 378, 'status' => 0],
        ['id' => 190, 'sortname' => 'ST', 'name' => 'Sao Tome and Principe', 'phonecode' => 239, 'status' => 0],
        ['id' => 191, 'sortname' => 'SA', 'name' => 'Saudi Arabia', 'phonecode' => 966, 'status' => 0],
        ['id' => 192, 'sortname' => 'SN', 'name' => 'Senegal', 'phonecode' => 221, 'status' => 0],
        ['id' => 193, 'sortname' => 'RS', 'name' => 'Serbia', 'phonecode' => 381, 'status' => 0],
        ['id' => 194, 'sortname' => 'SC', 'name' => 'Seychelles', 'phonecode' => 248, 'status' => 0],
        ['id' => 195, 'sortname' => 'SL', 'name' => 'Sierra Leone', 'phonecode' => 232, 'status' => 0],
        ['id' => 196, 'sortname' => 'SG', 'name' => 'Singapore', 'phonecode' => 65, 'status' => 0],
        ['id' => 197, 'sortname' => 'SK', 'name' => 'Slovakia', 'phonecode' => 421, 'status' => 0],
        ['id' => 198, 'sortname' => 'SI', 'name' => 'Slovenia', 'phonecode' => 386, 'status' => 0],
        ['id' => 199, 'sortname' => 'XG', 'name' => 'Smaller Territories of the UK', 'phonecode' => 44, 'status' => 0],
        ['id' => 200, 'sortname' => 'SB', 'name' => 'Solomon Islands', 'phonecode' => 677, 'status' => 0],
        ['id' => 201, 'sortname' => 'SO', 'name' => 'Somalia', 'phonecode' => 252, 'status' => 0],
        ['id' => 202, 'sortname' => 'ZA', 'name' => 'South Africa', 'phonecode' => 27, 'status' => 0],
        ['id' => 203, 'sortname' => 'GS', 'name' => 'South Georgia', 'phonecode' => 0, 'status' => 0],
        ['id' => 204, 'sortname' => 'SS', 'name' => 'South Sudan', 'phonecode' => 211, 'status' => 0],
        ['id' => 205, 'sortname' => 'ES', 'name' => 'Spain', 'phonecode' => 34, 'status' => 0],
        ['id' => 206, 'sortname' => 'LK', 'name' => 'Sri Lanka', 'phonecode' => 94, 'status' => 0],
        ['id' => 207, 'sortname' => 'SD', 'name' => 'Sudan', 'phonecode' => 249, 'status' => 0],
        ['id' => 208, 'sortname' => 'SR', 'name' => 'Suriname', 'phonecode' => 597, 'status' => 0],
        ['id' => 209, 'sortname' => 'SJ', 'name' => 'Svalbard And Jan Mayen Islands', 'phonecode' => 47, 'status' => 0],
        ['id' => 210, 'sortname' => 'SZ', 'name' => 'Swaziland', 'phonecode' => 268, 'status' => 0],
        ['id' => 211, 'sortname' => 'SE', 'name' => 'Sweden', 'phonecode' => 46, 'status' => 0],
        ['id' => 212, 'sortname' => 'CH', 'name' => 'Switzerland', 'phonecode' => 41, 'status' => 0],
        ['id' => 213, 'sortname' => 'SY', 'name' => 'Syria', 'phonecode' => 963, 'status' => 0],
        ['id' => 214, 'sortname' => 'TW', 'name' => 'Taiwan', 'phonecode' => 886, 'status' => 0],
        ['id' => 215, 'sortname' => 'TJ', 'name' => 'Tajikistan', 'phonecode' => 992, 'status' => 0],
        ['id' => 216, 'sortname' => 'TZ', 'name' => 'Tanzania', 'phonecode' => 255, 'status' => 0],
        ['id' => 217, 'sortname' => 'TH', 'name' => 'Thailand', 'phonecode' => 66, 'status' => 0],
        ['id' => 218, 'sortname' => 'TG', 'name' => 'Togo', 'phonecode' => 228, 'status' => 0],
        ['id' => 219, 'sortname' => 'TK', 'name' => 'Tokelau', 'phonecode' => 690, 'status' => 0],
        ['id' => 220, 'sortname' => 'TO', 'name' => 'Tonga', 'phonecode' => 676, 'status' => 0],
        ['id' => 221, 'sortname' => 'TT', 'name' => 'Trinidad And Tobago', 'phonecode' => 1868, 'status' => 0],
        ['id' => 222, 'sortname' => 'TN', 'name' => 'Tunisia', 'phonecode' => 216, 'status' => 0],
        ['id' => 223, 'sortname' => 'TR', 'name' => 'Turkey', 'phonecode' => 90, 'status' => 0],
        ['id' => 224, 'sortname' => 'TM', 'name' => 'Turkmenistan', 'phonecode' => 7370, 'status' => 0],
        ['id' => 225, 'sortname' => 'TC', 'name' => 'Turks And Caicos Islands', 'phonecode' => 1649, 'status' => 0],
        ['id' => 226, 'sortname' => 'TV', 'name' => 'Tuvalu', 'phonecode' => 688, 'status' => 0],
        ['id' => 227, 'sortname' => 'UG', 'name' => 'Uganda', 'phonecode' => 256, 'status' => 0],
        ['id' => 228, 'sortname' => 'UA', 'name' => 'Ukraine', 'phonecode' => 380, 'status' => 0],
        ['id' => 229, 'sortname' => 'AE', 'name' => 'United Arab Emirates', 'phonecode' => 971, 'status' => 0],
        ['id' => 230, 'sortname' => 'GB', 'name' => 'United Kingdom', 'phonecode' => 44, 'status' => 0],
        ['id' => 231, 'sortname' => 'US', 'name' => 'United States', 'phonecode' => 1, 'status' => 1],
        ['id' => 232, 'sortname' => 'UM', 'name' => 'United States Minor Outlying Islands', 'phonecode' => 1, 'status' => 0],
        ['id' => 233, 'sortname' => 'UY', 'name' => 'Uruguay', 'phonecode' => 598, 'status' => 0],
        ['id' => 234, 'sortname' => 'UZ', 'name' => 'Uzbekistan', 'phonecode' => 998, 'status' => 0],
        ['id' => 235, 'sortname' => 'VU', 'name' => 'Vanuatu', 'phonecode' => 678, 'status' => 0],
        ['id' => 236, 'sortname' => 'VA', 'name' => 'Vatican City State (Holy See)', 'phonecode' => 39, 'status' => 0],
        ['id' => 237, 'sortname' => 'VE', 'name' => 'Venezuela', 'phonecode' => 58, 'status' => 0],
        ['id' => 238, 'sortname' => 'VN', 'name' => 'Vietnam', 'phonecode' => 84, 'status' => 0],
        ['id' => 239, 'sortname' => 'VG', 'name' => 'Virgin Islands (British)', 'phonecode' => 1284, 'status' => 0],
        ['id' => 240, 'sortname' => 'VI', 'name' => 'Virgin Islands (US)', 'phonecode' => 1340, 'status' => 0],
        ['id' => 241, 'sortname' => 'WF', 'name' => 'Wallis And Futuna Islands', 'phonecode' => 681, 'status' => 0],
        ['id' => 242, 'sortname' => 'EH', 'name' => 'Western Sahara', 'phonecode' => 212, 'status' => 0],
        ['id' => 243, 'sortname' => 'YE', 'name' => 'Yemen', 'phonecode' => 967, 'status' => 0],
        ['id' => 244, 'sortname' => 'YU', 'name' => 'Yugoslavia', 'phonecode' => 38, 'status' => 0],
        ['id' => 245, 'sortname' => 'ZM', 'name' => 'Zambia', 'phonecode' => 260, 'status' => 0],
        ['id' => 246, 'sortname' => 'ZW', 'name' => 'Zimbabwe', 'phonecode' => 263, 'status' => 0],
        ]);
    }
}
