<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class ShopStatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shop_states')->insert([
            ['id' => 1, 'name' => 'Andaman and Nicobar Islands', 'country_id' => 101],
            ['id' => 2, 'name' => 'Andhra Pradesh', 'country_id' => 101],
            ['id' => 3, 'name' => 'Arunachal Pradesh', 'country_id' => 101],
            ['id' => 4, 'name' => 'Assam', 'country_id' => 101],
            ['id' => 5, 'name' => 'Bihar', 'country_id' => 101],
            ['id' => 6, 'name' => 'Chandigarh', 'country_id' => 101],
            ['id' => 7, 'name' => 'Chhattisgarh', 'country_id' => 101],
            ['id' => 8, 'name' => 'Dadra and Nagar Haveli', 'country_id' => 101],
            ['id' => 9, 'name' => 'Daman and Diu', 'country_id' => 101],
            ['id' => 10, 'name' => 'Delhi', 'country_id' => 101],
            ['id' => 11, 'name' => 'Goa', 'country_id' => 101],
            ['id' => 12, 'name' => 'Gujarat', 'country_id' => 101],
            ['id' => 13, 'name' => 'Haryana', 'country_id' => 101],
            ['id' => 14, 'name' => 'Himachal Pradesh', 'country_id' => 101],
            ['id' => 15, 'name' => 'Jammu and Kashmir', 'country_id' => 101],
            ['id' => 16, 'name' => 'Jharkhand', 'country_id' => 101],
            ['id' => 17, 'name' => 'Karnataka', 'country_id' => 101],
            ['id' => 18, 'name' => 'Kenmore', 'country_id' => 101],
            ['id' => 19, 'name' => 'Kerala', 'country_id' => 101],
            ['id' => 20, 'name' => 'Lakshadweep', 'country_id' => 101],
            ['id' => 21, 'name' => 'Madhya Pradesh', 'country_id' => 101],
            ['id' => 22, 'name' => 'Maharashtra', 'country_id' => 101],
            ['id' => 23, 'name' => 'Manipur', 'country_id' => 101],
            ['id' => 24, 'name' => 'Meghalaya', 'country_id' => 101],
            ['id' => 25, 'name' => 'Mizoram', 'country_id' => 101],
            ['id' => 26, 'name' => 'Nagaland', 'country_id' => 101],
            ['id' => 27, 'name' => 'Narora', 'country_id' => 101],
            ['id' => 28, 'name' => 'Natwar', 'country_id' => 101],
            ['id' => 29, 'name' => 'Odisha', 'country_id' => 101],
            ['id' => 30, 'name' => 'Paschim Medinipur', 'country_id' => 101],
            ['id' => 31, 'name' => 'Pondicherry', 'country_id' => 101],
            ['id' => 32, 'name' => 'Punjab', 'country_id' => 101],
            ['id' => 33, 'name' => 'Rajasthan', 'country_id' => 101],
            ['id' => 34, 'name' => 'Sikkim', 'country_id' => 101],
            ['id' => 35, 'name' => 'Tamil Nadu', 'country_id' => 101],
            ['id' => 36, 'name' => 'Telangana', 'country_id' => 101],
            ['id' => 37, 'name' => 'Tripura', 'country_id' => 101],
            ['id' => 38, 'name' => 'Uttar Pradesh', 'country_id' => 101],
            ['id' => 39, 'name' => 'Uttarakhand', 'country_id' => 101],
            ['id' => 40, 'name' => 'Vaishali', 'country_id' => 101],
            ['id' => 41, 'name' => 'West Bengal', 'country_id' => 101],
            ['id' => 42, 'name' => 'Badakhshan', 'country_id' => 1],
            ['id' => 43, 'name' => 'Badgis', 'country_id' => 1],
            ['id' => 44, 'name' => 'Baglan', 'country_id' => 1],
            ['id' => 45, 'name' => 'Balkh', 'country_id' => 1],
            ['id' => 46, 'name' => 'Bamiyan', 'country_id' => 1],
            ['id' => 47, 'name' => 'Farah', 'country_id' => 1],
            ['id' => 48, 'name' => 'Faryab', 'country_id' => 1],
            ['id' => 49, 'name' => 'Gawr', 'country_id' => 1],
            ['id' => 50, 'name' => 'Gazni', 'country_id' => 1],
            ['id' => 51, 'name' => 'Herat', 'country_id' => 1],
            ['id' => 52, 'name' => 'Hilmand', 'country_id' => 1],
            ['id' => 53, 'name' => 'Jawzjan', 'country_id' => 1],
            ['id' => 54, 'name' => 'Kabul', 'country_id' => 1],
            ['id' => 55, 'name' => 'Kapisa', 'country_id' => 1],
            ['id' => 56, 'name' => 'Khawst', 'country_id' => 1],
            ['id' => 57, 'name' => 'Kunar', 'country_id' => 1],
            ['id' => 58, 'name' => 'Lagman', 'country_id' => 1],
            ['id' => 59, 'name' => 'Lawghar', 'country_id' => 1],
            ['id' => 60, 'name' => 'Nangarhar', 'country_id' => 1],
            ['id' => 61, 'name' => 'Nimruz', 'country_id' => 1],
            ['id' => 62, 'name' => 'Nuristan', 'country_id' => 1],
            ['id' => 63, 'name' => 'Paktika', 'country_id' => 1],
            ['id' => 64, 'name' => 'Paktiya', 'country_id' => 1],
            ['id' => 65, 'name' => 'Parwan', 'country_id' => 1],
            ['id' => 66, 'name' => 'Qandahar', 'country_id' => 1],
            ['id' => 67, 'name' => 'Qunduz', 'country_id' => 1],
            ['id' => 68, 'name' => 'Samangan', 'country_id' => 1],
            ['id' => 69, 'name' => 'Sar-e Pul', 'country_id' => 1],
            ['id' => 70, 'name' => 'Takhar', 'country_id' => 1],
            ['id' => 71, 'name' => 'Uruzgan', 'country_id' => 1],
            ['id' => 72, 'name' => 'Wardag', 'country_id' => 1],
            ['id' => 73, 'name' => 'Zabul', 'country_id' => 1],
            ['id' => 74, 'name' => 'Berat', 'country_id' => 2],
            ['id' => 75, 'name' => 'Bulqize', 'country_id' => 2],
            ['id' => 76, 'name' => 'Delvine', 'country_id' => 2],
            ['id' => 77, 'name' => 'Devoll', 'country_id' => 2],
            ['id' => 78, 'name' => 'Dibre', 'country_id' => 2],
            ['id' => 79, 'name' => 'Durres', 'country_id' => 2],
            ['id' => 80, 'name' => 'Elbasan', 'country_id' => 2],
            ['id' => 81, 'name' => 'Fier', 'country_id' => 2],
            ['id' => 82, 'name' => 'Gjirokaster', 'country_id' => 2],
            ['id' => 83, 'name' => 'Korca', 'country_id' => 2],
            ['id' => 84, 'name' => 'Kukes', 'country_id' => 2],
            ['id' => 85, 'name' => 'Shkoder', 'country_id' => 2],
            ['id' => 86, 'name' => 'Tirane', 'country_id' => 2],
            ['id' => 87, 'name' => 'Vlorë', 'country_id' => 2],
            ['id' => 88, 'name' => 'Ampara', 'country_id' => 3],
            ['id' => 89, 'name' => 'Anuradhapura', 'country_id' => 3],
            ['id' => 90, 'name' => 'Badulla', 'country_id' => 3],
            ['id' => 91, 'name' => 'Batticaloa', 'country_id' => 3],
            ['id' => 92, 'name' => 'Colombo', 'country_id' => 3],
            ['id' => 93, 'name' => 'Galle', 'country_id' => 3],
            ['id' => 94, 'name' => 'Gampaha', 'country_id' => 3],
            ['id' => 95, 'name' => 'Hambantota', 'country_id' => 3],
            ['id' => 96, 'name' => 'Jaffna', 'country_id' => 3],
            ['id' => 97, 'name' => 'Kalutara', 'country_id' => 3],
            ['id' => 98, 'name' => 'Kandy', 'country_id' => 3],
            ['id' => 99, 'name' => 'Kegalle', 'country_id' => 3],
            ['id' => 100, 'name' => 'Kilinochchi', 'country_id' => 3],
            ['id' => 101, 'name' => 'Kurunegala', 'country_id' => 3],
            ['id' => 102, 'name' => 'Mannar', 'country_id' => 3],
            ['id' => 103, 'name' => 'Matale', 'country_id' => 3],
            ['id' => 104, 'name' => 'Matara', 'country_id' => 3],
            ['id' => 105, 'name' => 'Monaragala', 'country_id' => 3],
            ['id' => 106, 'name' => 'Mullaitivu', 'country_id' => 3],
            ['id' => 107, 'name' => 'Nuwara Eliya', 'country_id' => 3],
            ['id' => 108, 'name' => 'Polonnaruwa', 'country_id' => 3],
            ['id' => 109, 'name' => 'Puttalam', 'country_id' => 3],
            ['id' => 110, 'name' => 'Ratnapura', 'country_id' => 3],
            ['id' => 111, 'name' => 'Trincomalee', 'country_id' => 3],
            ['id' => 112, 'name' => 'Vavuniya', 'country_id' => 3],
            ['id' => 113, 'name' => 'Antananarivo', 'country_id' => 4],
            ['id' => 114, 'name' => 'Fianarantsoa', 'country_id' => 4],
            ['id' => 115, 'name' => 'Mahajanga', 'country_id' => 4],
            ['id' => 116, 'name' => 'Toamasina', 'country_id' => 4],
            ['id' => 117, 'name' => 'Toliara', 'country_id' => 4],
            ['id' => 118, 'name' => 'Alfred Nzo', 'country_id' => 5],
            ['id' => 119, 'name' => 'Amatole', 'country_id' => 5],
            ['id' => 120, 'name' => 'Cape Town', 'country_id' => 5],
            ['id' => 121, 'name' => 'Cedarberg', 'country_id' => 5],
            ['id' => 122, 'name' => 'Chris Hani', 'country_id' => 5],
            ['id' => 123, 'name' => 'Ehlanzeni', 'country_id' => 5],
            ['id' => 124, 'name' => 'Fezile Dabi', 'country_id' => 5],
            ['id' => 125, 'name' => 'Gauteng', 'country_id' => 5],
            ['id' => 126, 'name' => 'Giyani', 'country_id' => 5],
            ['id' => 127, 'name' => 'Harry Gwala', 'country_id' => 5],
            ['id' => 128, 'name' => 'Inland', 'country_id' => 5],
            ['id' => 129, 'name' => 'Mopani', 'country_id' => 5],
            ['id' => 130, 'name' => 'Nelson Mandela Bay', 'country_id' => 5],
            ['id' => 131, 'name' => 'O R Tambo', 'country_id' => 5],
            ['id' => 132, 'name' => 'Overberg', 'country_id' => 5],
            ['id' => 133, 'name' => 'Pofadder', 'country_id' => 5],
            ['id' => 134, 'name' => 'Sedibeng', 'country_id' => 5],
            ['id' => 135, 'name' => 'Sol Plaatje', 'country_id' => 5],
            ['id' => 136, 'name' => 'Thabo Mofutsanyana', 'country_id' => 5],
            ['id' => 137, 'name' => 'Ugu District', 'country_id' => 5],
            ['id' => 138, 'name' => 'Uthukela', 'country_id' => 5],
            ['id' => 139, 'name' => 'Waterberg', 'country_id' => 5],
            ['id' => 140, 'name' => 'Zululand', 'country_id' => 5],
            ['id' => 141, 'name' => 'Buenos Aires', 'country_id' => 6],
            ['id' => 142, 'name' => 'Catamarca', 'country_id' => 6],
            ['id' => 143, 'name' => 'Chaco', 'country_id' => 6],
            ['id' => 144, 'name' => 'Chubut', 'country_id' => 6],
            ['id' => 145, 'name' => 'Cordoba', 'country_id' => 6],
            ['id' => 146, 'name' => 'Corrientes', 'country_id' => 6],
            ['id' => 147, 'name' => 'Entre Ríos', 'country_id' => 6],
            ['id' => 148, 'name' => 'Formosa', 'country_id' => 6],
            ['id' => 149, 'name' => 'Jujuy', 'country_id' => 6],
            ['id' => 150, 'name' => 'La Pampa', 'country_id' => 6],
            ['id' => 151, 'name' => 'La Rioja', 'country_id' => 6],
            ['id' => 152, 'name' => 'Mendoza', 'country_id' => 6],
            ['id' => 153, 'name' => 'Misiones', 'country_id' => 6],
            ['id' => 154, 'name' => 'Neuquén', 'country_id' => 6],
            ['id' => 155, 'name' => 'Río Negro', 'country_id' => 6],
            ['id' => 156, 'name' => 'Salta', 'country_id' => 6],
            ['id' => 157, 'name' => 'San Juan', 'country_id' => 6],
            ['id' => 158, 'name' => 'San Luis', 'country_id' => 6],
            ['id' => 159, 'name' => 'Santa Cruz', 'country_id' => 6],
            ['id' => 160, 'name' => 'Santa Fe', 'country_id' => 6],
            ['id' => 161, 'name' => 'Santiago del Estero', 'country_id' => 6],
            ['id' => 162, 'name' => 'Tierra del Fuego', 'country_id' => 6],
            ['id' => 163, 'name' => 'Tucumán', 'country_id' => 6],
            ['id' => 164, 'name' => 'Fukuoka', 'country_id' => 7],
            ['id' => 165, 'name' => 'Aichi', 'country_id' => 7],
            ['id' => 166, 'name' => 'Akita', 'country_id' => 7],
            ['id' => 167, 'name' => 'Aomori', 'country_id' => 7],
            ['id' => 168, 'name' => 'Chiba', 'country_id' => 7],
            ['id' => 169, 'name' => 'Ehime', 'country_id' => 7],
            ['id' => 170, 'name' => 'Fukui', 'country_id' => 7],
            ['id' => 171, 'name' => 'Gifu', 'country_id' => 7],
            ['id' => 172, 'name' => 'Gunma', 'country_id' => 7],
            ['id' => 173, 'name' => 'Hiroshima', 'country_id' => 7],
            ['id' => 174, 'name' => 'Hokkaido', 'country_id' => 7],
            ['id' => 175, 'name' => 'Hyogo', 'country_id' => 7],
            ['id' => 176, 'name' => 'Ibaraki', 'country_id' => 7],
            ['id' => 177, 'name' => 'Ishikawa', 'country_id' => 7],
            ['id' => 178, 'name' => 'Iwate', 'country_id' => 7],
            ['id' => 179, 'name' => 'Kagawa', 'country_id' => 7],
            ['id' => 180, 'name' => 'Kagoshima', 'country_id' => 7],
            ['id' => 181, 'name' => 'Kanagawa', 'country_id' => 7],
            ['id' => 182, 'name' => 'Kochi', 'country_id' => 7],
            ['id' => 183, 'name' => 'Kumamoto', 'country_id' => 7],
            ['id' => 184, 'name' => 'Kyoto', 'country_id' => 7],
            ['id' => 185, 'name' => 'Mie', 'country_id' => 7],
            ['id' => 186, 'name' => 'Miyagi', 'country_id' => 7],
            ['id' => 187, 'name' => 'Miyazaki', 'country_id' => 7],
            ['id' => 188, 'name' => 'Nagano', 'country_id' => 7],
            ['id' => 189, 'name' => 'Nagasaki', 'country_id' => 7],
            ['id' => 190, 'name' => 'Nara', 'country_id' => 7],
            ['id' => 191, 'name' => 'Niigata', 'country_id' => 7],
            ['id' => 192, 'name' => 'Okinawa', 'country_id' => 7],
            ['id' => 193, 'name' => 'Osaka', 'country_id' => 7],
            ['id' => 194, 'name' => 'Saga', 'country_id' => 7],
            ['id' => 195, 'name' => 'Saitama', 'country_id' => 7],
            ['id' => 196, 'name' => 'Shiga', 'country_id' => 7],
            ['id' => 197, 'name' => 'Shimane', 'country_id' => 7],
            ['id' => 198, 'name' => 'Shizuoka', 'country_id' => 7],
            ['id' => 199, 'name' => 'Tochigi', 'country_id' => 7],
            ['id' => 200, 'name' => 'Tokyo', 'country_id' => 7],

            ['id' => 201, 'name' => 'Barbuda', 'country_id' => 9],
            ['id' => 202, 'name' => 'Saint George', 'country_id' => 9],
            ['id' => 203, 'name' => 'Saint John', 'country_id' => 9],
            ['id' => 204, 'name' => 'Saint Mary', 'country_id' => 9],
            ['id' => 205, 'name' => 'Saint Paul', 'country_id' => 9],
            ['id' => 206, 'name' => 'Saint Peter', 'country_id' => 9],
            ['id' => 207, 'name' => 'Saint Philip', 'country_id' => 9],
            ['id' => 208, 'name' => 'Buenos Aires', 'country_id' => 10],
            ['id' => 209, 'name' => 'Catamarca', 'country_id' => 10],
            ['id' => 210, 'name' => 'Chaco', 'country_id' => 10],
            ['id' => 211, 'name' => 'Chubut', 'country_id' => 10],
            ['id' => 212, 'name' => 'Cordoba', 'country_id' => 10],
            ['id' => 213, 'name' => 'Corrientes', 'country_id' => 10],
            ['id' => 214, 'name' => 'Distrito Federal', 'country_id' => 10],
            ['id' => 215, 'name' => 'Entre Rios', 'country_id' => 10],
            ['id' => 216, 'name' => 'Formosa', 'country_id' => 10],
            ['id' => 217, 'name' => 'Jujuy', 'country_id' => 10],
            ['id' => 218, 'name' => 'La Pampa', 'country_id' => 10],
            ['id' => 219, 'name' => 'La Rioja', 'country_id' => 10],
            ['id' => 220, 'name' => 'Mendoza', 'country_id' => 10],
            ['id' => 221, 'name' => 'Misiones', 'country_id' => 10],
            ['id' => 222, 'name' => 'Neuquen', 'country_id' => 10],
            ['id' => 223, 'name' => 'Rio Negro', 'country_id' => 10],
            ['id' => 224, 'name' => 'Salta', 'country_id' => 10],
            ['id' => 225, 'name' => 'San Juan', 'country_id' => 10],
            ['id' => 226, 'name' => 'San Luis', 'country_id' => 10],
            ['id' => 227, 'name' => 'Santa Cruz', 'country_id' => 10],
            ['id' => 228, 'name' => 'Santa Fe', 'country_id' => 10],
            ['id' => 229, 'name' => 'Santiago del Estero', 'country_id' => 10],
            ['id' => 230, 'name' => 'Tierra del Fuego', 'country_id' => 10],
            ['id' => 231, 'name' => 'Tucuman', 'country_id' => 10],
            ['id' => 232, 'name' => 'Aragatsotn', 'country_id' => 11],
            ['id' => 233, 'name' => 'Ararat', 'country_id' => 11],
            ['id' => 234, 'name' => 'Armavir', 'country_id' => 11],
            ['id' => 235, 'name' => 'Gegharkunik', 'country_id' => 11],
            ['id' => 236, 'name' => 'Kotaik', 'country_id' => 11],
            ['id' => 237, 'name' => 'Lori', 'country_id' => 11],
            ['id' => 238, 'name' => 'Shirak', 'country_id' => 11],
            ['id' => 239, 'name' => 'Stepanakert', 'country_id' => 11],
            ['id' => 240, 'name' => 'Syunik', 'country_id' => 11],
            ['id' => 241, 'name' => 'Tavush', 'country_id' => 11],
            ['id' => 242, 'name' => 'Vayots Dzor', 'country_id' => 11],
            ['id' => 243, 'name' => 'Yerevan', 'country_id' => 11],
            ['id' => 244, 'name' => 'Aruba', 'country_id' => 12],
            ['id' => 245, 'name' => 'Auckland', 'country_id' => 13],
            ['id' => 246, 'name' => 'Australian Capital Territory', 'country_id' => 13],
            ['id' => 247, 'name' => 'Balgowlah', 'country_id' => 13],
            ['id' => 248, 'name' => 'Balmain', 'country_id' => 13],
            ['id' => 249, 'name' => 'Bankstown', 'country_id' => 13],
            ['id' => 250, 'name' => 'Baulkham Hills', 'country_id' => 13],
            ['id' => 251, 'name' => 'Bonnet Bay', 'country_id' => 13],
            ['id' => 252, 'name' => 'Camberwell', 'country_id' => 13],
            ['id' => 253, 'name' => 'Carole Park', 'country_id' => 13],
            ['id' => 254, 'name' => 'Castle Hill', 'country_id' => 13],
            ['id' => 255, 'name' => 'Caulfield', 'country_id' => 13],
            ['id' => 256, 'name' => 'Chatswood', 'country_id' => 13],
            ['id' => 257, 'name' => 'Cheltenham', 'country_id' => 13],
            ['id' => 258, 'name' => 'Cherrybrook', 'country_id' => 13],
            ['id' => 259, 'name' => 'Clayton', 'country_id' => 13],
            ['id' => 260, 'name' => 'Collingwood', 'country_id' => 13],
            ['id' => 261, 'name' => 'Frenchs Forest', 'country_id' => 13],
            ['id' => 262, 'name' => 'Hawthorn', 'country_id' => 13],
            ['id' => 263, 'name' => 'Jannnali', 'country_id' => 13],
            ['id' => 264, 'name' => 'Knoxfield', 'country_id' => 13],
            ['id' => 265, 'name' => 'Melbourne', 'country_id' => 13],
            ['id' => 266, 'name' => 'New South Wales', 'country_id' => 13],
            ['id' => 267, 'name' => 'Northern Territory', 'country_id' => 13],
            ['id' => 268, 'name' => 'Perth', 'country_id' => 13],
            ['id' => 269, 'name' => 'Queensland', 'country_id' => 13],
            ['id' => 270, 'name' => 'South Australia', 'country_id' => 13],
            ['id' => 271, 'name' => 'Tasmania', 'country_id' => 13],
            ['id' => 272, 'name' => 'Templestowe', 'country_id' => 13],
            ['id' => 273, 'name' => 'Victoria', 'country_id' => 13],
            ['id' => 274, 'name' => 'Werribee south', 'country_id' => 13],
            ['id' => 275, 'name' => 'Western Australia', 'country_id' => 13],
            ['id' => 276, 'name' => 'Wheeler', 'country_id' => 13],
            ['id' => 277, 'name' => 'Bundesland Salzburg', 'country_id' => 14],
            ['id' => 278, 'name' => 'Bundesland Steiermark', 'country_id' => 14],
            ['id' => 279, 'name' => 'Bundesland Tirol', 'country_id' => 14],
            ['id' => 280, 'name' => 'Burgenland', 'country_id' => 14],
            ['id' => 281, 'name' => 'Carinthia', 'country_id' => 14],
            ['id' => 282, 'name' => 'Lower Austria', 'country_id' => 14],
            ['id' => 283, 'name' => 'Upper Austria', 'country_id' => 14],
            ['id' => 284, 'name' => 'Vienna', 'country_id' => 14],
            ['id' => 285, 'name' => 'Vorarlberg', 'country_id' => 14],
            ['id' => 286, 'name' => 'Lima', 'country_id' => 15],
            ['id' => 287, 'name' => 'Callao', 'country_id' => 15],
            ['id' => 288, 'name' => 'Cusco', 'country_id' => 15],
            ['id' => 289, 'name' => 'Arequipa', 'country_id' => 15],
            ['id' => 290, 'name' => 'Puno', 'country_id' => 15],
            ['id' => 291, 'name' => 'Junin', 'country_id' => 15],
            ['id' => 292, 'name' => 'La Libertad', 'country_id' => 15],
            ['id' => 293, 'name' => 'Piura', 'country_id' => 15],
            ['id' => 294, 'name' => 'Amazonas', 'country_id' => 15],
            ['id' => 295, 'name' => 'Ancash', 'country_id' => 15],
            ['id' => 296, 'name' => 'San Martin', 'country_id' => 15],
            ['id' => 297, 'name' => 'Ica', 'country_id' => 15],
            ['id' => 298, 'name' => 'Ayacucho', 'country_id' => 15],
            ['id' => 299, 'name' => 'Huancavelica', 'country_id' => 15],
            ['id' => 300, 'name' => 'Tumbes', 'country_id' => 15],
            ['id' => 301, 'name' => 'Moquegua', 'country_id' => 15],
            ['id' => 302, 'name' => 'Tacna', 'country_id' => 15],
            ['id' => 303, 'name' => 'Chimbote', 'country_id' => 15],
            ['id' => 304, 'name' => 'Chachapoyas', 'country_id' => 15],
            ['id' => 305, 'name' => 'Callao Region', 'country_id' => 15],
            ['id' => 306, 'name' => 'Oruro', 'country_id' => 16],
            ['id' => 307, 'name' => 'La Paz', 'country_id' => 16],
            ['id' => 308, 'name' => 'Santa Cruz', 'country_id' => 16],
            ['id' => 309, 'name' => 'Cochabamba', 'country_id' => 16],
            ['id' => 310, 'name' => 'Tarija', 'country_id' => 16],
            ['id' => 311, 'name' => 'Sucre', 'country_id' => 16],
            ['id' => 312, 'name' => 'Potosi', 'country_id' => 16],
            ['id' => 313, 'name' => 'Beni', 'country_id' => 16],
            ['id' => 314, 'name' => 'Chuquisaca', 'country_id' => 16],
            ['id' => 315, 'name' => 'El Alto', 'country_id' => 16],
            ['id' => 316, 'name' => 'Carabobo', 'country_id' => 17],
            ['id' => 317, 'name' => 'Falcón', 'country_id' => 17],
            ['id' => 318, 'name' => 'Distrito Capital', 'country_id' => 17],
            ['id' => 319, 'name' => 'Barinas', 'country_id' => 17],
            ['id' => 320, 'name' => 'Aragua', 'country_id' => 17],
            ['id' => 321, 'name' => 'Anzoátegui', 'country_id' => 17],
            ['id' => 322, 'name' => 'Táchira', 'country_id' => 17],
            ['id' => 323, 'name' => 'Zulia', 'country_id' => 17],
            ['id' => 324, 'name' => 'Nueva Esparta', 'country_id' => 17],
            ['id' => 325, 'name' => 'Lara', 'country_id' => 17],
            ['id' => 326, 'name' => 'Miranda', 'country_id' => 17],
            ['id' => 327, 'name' => 'Sucre', 'country_id' => 17],
            ['id' => 328, 'name' => 'Yaracuy', 'country_id' => 17],
            ['id' => 329, 'name' => 'Monagas', 'country_id' => 17],
            ['id' => 330, 'name' => 'Vargas', 'country_id' => 17],
            ['id' => 331, 'name' => 'Delta Amacuro', 'country_id' => 17],
            ['id' => 332, 'name' => 'Guárico', 'country_id' => 17],
            ['id' => 333, 'name' => 'Bolívar', 'country_id' => 17],
            ['id' => 334, 'name' => 'Amazonas', 'country_id' => 17],
            ['id' => 335, 'name' => 'Apure', 'country_id' => 17],
            ['id' => 336, 'name' => 'Cojedes', 'country_id' => 17],
            ['id' => 337, 'name' => 'Mérida', 'country_id' => 17],
            ['id' => 338, 'name' => 'Guayana', 'country_id' => 17],
            ['id' => 339, 'name' => 'Trujillo', 'country_id' => 17],
            ['id' => 340, 'name' => 'Valles del Tuy', 'country_id' => 17],
            ['id' => 341, 'name' => 'Acarigua', 'country_id' => 17],
            ['id' => 342, 'name' => 'Valencia', 'country_id' => 17],
            ['id' => 343, 'name' => 'San Juan de los Morros', 'country_id' => 17],
            ['id' => 344, 'name' => 'San Fernando de Apure', 'country_id' => 17],
            ['id' => 345, 'name' => 'Ciudad Guayana', 'country_id' => 17],
            ['id' => 346, 'name' => 'Carúpano', 'country_id' => 17],
            ['id' => 347, 'name' => 'Puerto La Cruz', 'country_id' => 17],
            ['id' => 348, 'name' => 'Maturín', 'country_id' => 17],
            ['id' => 349, 'name' => 'Maracay', 'country_id' => 17],
            ['id' => 350, 'name' => 'El Tigre', 'country_id' => 17],
            ['id' => 351, 'name' => 'Cumana', 'country_id' => 17],
            ['id' => 352, 'name' => 'Carabobo', 'country_id' => 17],
            ['id' => 353, 'name' => 'Barquisimeto', 'country_id' => 17],
            ['id' => 354, 'name' => 'Coros', 'country_id' => 17],
            ['id' => 355, 'name' => 'Margarita', 'country_id' => 17],
            ['id' => 356, 'name' => 'Cumaná', 'country_id' => 17],
            ['id' => 357, 'name' => 'Santa Teresa', 'country_id' => 17],
            ['id' => 358, 'name' => 'Cúcuta', 'country_id' => 17],
            ['id' => 359, 'name' => 'Sucre', 'country_id' => 17],
            ['id' => 360, 'name' => 'María', 'country_id' => 17],
            // Add more entries until 200
        ]);
    }
}
